# Generated by Django 5.0.1 on 2024-03-26 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='attendence_data',
            new_name='attendence_date',
        ),
    ]
