# Generated by Django 5.0.1 on 2024-03-26 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_attendence_data_attendance_attendence_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='attendence_date',
            new_name='attendence_data',
        ),
    ]
