# Generated by Django 5.0.1 on 2024-02-04 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='session_id',
            new_name='session_year_id',
        ),
    ]
