# Generated by Django 5.0.1 on 2024-03-24 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_student_leave'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_leave',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.student'),
        ),
    ]
