# Generated by Django 5.0.1 on 2024-02-07 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_staff_leave'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deerwalk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('age', models.IntegerField()),
                ('occupation', models.CharField(max_length=40)),
                ('college', models.CharField(max_length=20)),
            ],
        ),
    ]
